# Generated by Django 4.0.1 on 2022-04-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_messages_options_alter_room_options_room_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_scanned',
            field=models.BooleanField(default=False, verbose_name='Просмотрено'),
        ),
    ]
