# Generated by Django 4.0.1 on 2022-04-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_userprofile_slug'),
        ('chat', '0005_remove_messages_is_scanned'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_scanned',
            field=models.ManyToManyField(blank=True, to='blog.UserProfile', verbose_name='Кем просмотрено'),
        ),
    ]
