# Generated by Django 4.0.1 on 2022-04-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_messages_created_at_alter_messages_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='dislikes',
            field=models.BooleanField(default=False, verbose_name='Дизлайки'),
        ),
        migrations.AddField(
            model_name='messages',
            name='likes',
            field=models.BooleanField(default=False, verbose_name='Лайки'),
        ),
    ]
