# Generated by Django 4.0.1 on 2022-02-02 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='ОШИБКА - МОЖНО НЕ ЗАПОЛНЯТЬ', max_length=100, verbose_name='ОШИБКА - МОЖНО НЕ ЗАПОЛНЯТЬ'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m', verbose_name='Avatar')),
                ('author', models.CharField(max_length=100, verbose_name='Псевдоним, связан со статьями')),
                ('slug', models.SlugField(unique=True, verbose_name='Url')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Автора(ов)',
                'verbose_name_plural': 'Авторы статей',
                'ordering': ['-user'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='author2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.userprofile', verbose_name='Автор'),
        ),
    ]
