# Generated by Django 4.0.1 on 2022-02-22 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_userprofile_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author2',
        ),
        migrations.AddField(
            model_name='post',
            name='author_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.userprofile', verbose_name='Автор'),
        ),
    ]
