# Generated by Django 4.0.1 on 2022-02-23 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_at',), 'verbose_name': 'Комментарий(и)', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
