# Generated by Django 4.0.1 on 2022-02-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_userprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.CharField(blank=True, default='-', max_length=50, verbose_name='Url'),
        ),
    ]
