# Generated by Django 4.0.1 on 2022-03-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='author',
            field=models.CharField(blank=True, max_length=100, verbose_name='Псевдоним, связан со статьями'),
        ),
    ]
