# Generated by Django 4.0.1 on 2022-03-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_userprofile_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Url'),
        ),
    ]
